
export const START_REQUEST = "START_REQUEST";
export const PUT_PRODUCT_TO_STATE = "PUT_PRODUCT_TO_STATE";
export const GET_ERROR = "GET_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_ERROR = "LOGIN_REQUEST_ERROR";


export const BTN_LOCK = "BTN_LOCK";
export const CHANGE_NAME = "CHANGE_NAME";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";