export const MARKET_REQUEST = "MARKET_REQUEST";
export const MARKET_REQUEST_SUCCESS = "MARKET_REQUEST_SUCCESS";
export const MARKET_REQUEST_ERROR = "MARKET_REQUEST_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_ERROR = "LOGIN_REQUEST_ERROR";

export const PUT_ITEM_TO_CART = "PUT_ITEM_TO_CART";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";